### ISSUE TITLE
[FEATURE] - develop auth routes

### ISSUE THREAD

**Issue by EmilyMaryon** [parmesan-recipes/parmesan#18]
### Description
authentication routes are available at /api/v1/auth
### Completion Requirements
- [ ] registration
- [x] get user information, not logged in case
- [ ] check user auth
- [x] login
- [ ] logout
- [ ] database handler for all this
- [ ] add tests into /tests/routes/V1/auth.js

### Implementation Discussion (optional)
use off the shelf node module?

**Comment by ashleycma** [comment]
Fixed better in another issue
